import "./globals.css";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import GraphQLProvider from "@app/components/providers/GraphQLProvider";
import Layout from "@app/components/layout";
import { cn } from "@app/lib/utils";

const fontFamily = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={cn(fontFamily.className, "h-full bg-slate-50")}>
        <GraphQLProvider>
          <Layout>{children}</Layout>
        </GraphQLProvider>
      </body>
    </html>
  );
}
