import GraphQLProvider from "@app/providers/GraphQLProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";

const fontFamily = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fontFamily.className}>
        <GraphQLProvider>{children}</GraphQLProvider>
      </body>
    </html>
  );
}
